//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] biene {
            get {
                object obj = ResourceManager.GetObject("biene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;svg
        ///   width=&quot;623&quot;
        ///   height=&quot;623&quot;
        ///   overflow=&quot;hidden&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg12&quot;
        ///   sodipodi:docname=&quot;biene2.svg&quot;
        ///   inkscape:version=&quot;1.2 (dc2aedaf03, 2022-05-15)&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///   xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;sodipo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string insekt0 {
            get {
                return ResourceManager.GetString("insekt0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg width=&quot;403&quot; height=&quot;328&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; overflow=&quot;hidden&quot;&gt;&lt;defs&gt;&lt;clipPath id=&quot;clip0&quot;&gt;&lt;rect x=&quot;1121&quot; y=&quot;1367&quot; width=&quot;403&quot; height=&quot;328&quot;/&gt;&lt;/clipPath&gt;&lt;image width=&quot;403&quot; height=&quot;328&quot; xlink:href=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZMAAAFICAYAAACV5RONAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAMsAAADLAAShkWtsAAP+lSURBVHhe7P13tBTVuu6P379/496zWZ1z7l4555wIay1yzjlHARGQYCMggmSJgiAIKKKgiAlQl4oJiQqScxQkw0p4x3h+z1vdS3Dffc73hB1073rHeMas [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string insekt1 {
            get {
                return ResourceManager.GetString("insekt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg width=&quot;396&quot; height=&quot;395&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; overflow=&quot;hidden&quot;&gt;&lt;defs&gt;&lt;clipPath id=&quot;clip0&quot;&gt;&lt;rect x=&quot;1850&quot; y=&quot;1119&quot; width=&quot;396&quot; height=&quot;395&quot;/&gt;&lt;/clipPath&gt;&lt;image width=&quot;396&quot; height=&quot;395&quot; xlink:href=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYwAAAGLCAYAAADUPKXyAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAMsAAADLAAShkWtsAAP+lSURBVHhe7P3nl1xlmuYLn/9gPpw1s7r79PTbXdOmuqsKkEtvIjO89yYjMiLSe6tMpVIpE/LeIIc8AgRIeBBOgFACEhICIS+QhBzy3nt6neu9rycyqKqp [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string insekt2 {
            get {
                return ResourceManager.GetString("insekt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg width=&quot;495&quot; height=&quot;495&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; overflow=&quot;hidden&quot;&gt;&lt;defs&gt;&lt;clipPath id=&quot;clip0&quot;&gt;&lt;rect x=&quot;630&quot; y=&quot;98&quot; width=&quot;495&quot; height=&quot;495&quot;/&gt;&lt;/clipPath&gt;&lt;image width=&quot;495&quot; height=&quot;495&quot; xlink:href=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAe8AAAHvCAYAAAB9iVfNAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAMsAAADLAAShkWtsAAP+lSURBVHhe7P13dJzXmaeL9j/3tCUG5FAoVM45R1QECoVCzjlnkiAB5kwWMylmkRRFiVTO2QqW1ZLsshzk2O0O7nZPT9/pmfFMn9DnzMy5665z173rXv/uuz/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string insekt3 {
            get {
                return ResourceManager.GetString("insekt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;svg width=&quot;475&quot; height=&quot;475&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; overflow=&quot;hidden&quot;&gt;&lt;defs&gt;&lt;clipPath id=&quot;clip0&quot;&gt;&lt;rect x=&quot;1810&quot; y=&quot;387&quot; width=&quot;475&quot; height=&quot;475&quot;/&gt;&lt;/clipPath&gt;&lt;image width=&quot;475&quot; height=&quot;475&quot; xlink:href=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAMsAAADLAAShkWtsAAPU1SURBVHhe7L13fBRHvvX9/P8+N+w6kbPIKEtkTM4524BJJudsDDbGOWevc8A2GJMMNjZOIHIGIaGcc9YozGjy9HnPr6ZHCOy9d5+7994Fb53Pnq2eniRPN [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string insekt4 {
            get {
                return ResourceManager.GetString("insekt4", resourceCulture);
            }
        }
    }
}
